modLoader="javafml" #required
loaderVersion="[4,)" #required
credits="ErrorMikey" #optional
authors="STW Team" #optional
license="GNU GPL v3.0"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
    modId="survivaltweaks"
    version="${version}"
    displayName="Survival Tweaks"
    description="A collection of quality-of-life survival tweaks for Minecraft."

[[dependencies.survivaltweaks]]
    modId="neoforge"
    required=true
    versionRange="[${forge_version_range},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.survivaltweaks]]
    modId="minecraft"
    required=true
    versionRange="[${minecraft_version_range})"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config = 'survivaltweaks.mixins.json'
